### ISSUE TITLE
Render issue with Pegasus gate

### ISSUE THREAD

**Issue by oOKekeOo** [MineDragonCZ/Aunis1#116] opened 2022-03-05 22:16 UTC
I'm using Aunis 4.9.4.2
When I set a pegasus gate, the last block which should transform all the blocks into a gate causes a light blue screen and several seconds later, the game crash.
I get this message : "The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Rendering Block Entity
Code de sortie : -1"

There is the crash report in the attachments.
[crash-2022-03-05_22.49.39-client.txt](https://github.com/MineDragonCZ/Aunis1/files/8191577/crash-2022-03-05_22.49.39-client.txt)

Thank you for your time.

**Comment by MineDragonCZ** [comment] 2022-03-06 09:52
Duplicate of #115

**Closed by MineDragonCZ** 2022-03-06 09:52 UTC
