### ISSUE TITLE
Feature: IC2 integrations

### ISSUE THREAD

**Issue by DeathToCountry** [MineDragonCZ/Aunis1#136] opened 2022-04-08 02:15 UTC
Hi, I only have a suggestion for the power in associations with other mods, and that is to incorporate compatibilities with Industrial Craft 2's power blocks

**Comment by JimSkywalker** [comment] 2022-04-08 02:34
that is on the to do list already

**Comment by MineDragonCZ** [comment] 2022-04-08 03:59
Hi, its already planned :)

**Comment by MineDragonCZ** [comment] 2022-04-08 04:01
Duplicate of #86

**Closed by MineDragonCZ** 2022-04-08 04:01 UTC
Labels: Duplicate, Enhancement

**Comment by meclondrej** [comment] 2023-06-20 20:31
the Energy Converters mod is the proper solution
